name: Predict Games

on:
  schedule:
    - cron: "13 13 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  predict-games:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install Playwright browsers
        run: pnpm exec playwright install chromium

      - name: Predict results (Bundesliga Tippspiel)
        env:
          NODE_ENV: production
          KICKTIPP_USERNAME: ${{ secrets.KICKTIPP_USERNAME }}
          KICKTIPP_PASSWORD: ${{ secrets.KICKTIPP_PASSWORD }}
          KICKTIPP_GROUP_ID: bundesliga-tippspiel
          KICKTIPP_PREDICTION_STRATEGY: difference-ratio
        run: pnpm start

      - name: Predict results (private one)
        env:
          NODE_ENV: production
          KICKTIPP_USERNAME: ${{ secrets.KICKTIPP_USERNAME }}
          KICKTIPP_PASSWORD: ${{ secrets.KICKTIPP_PASSWORD }}
          KICKTIPP_GROUP_ID: ${{ secrets.KICKTIPP_GROUP_ID }}
          KICKTIPP_PREDICTION_STRATEGY: difference-ratio
        run: pnpm start
